# Generated by Django 5.1.5 on 2025-02-04 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250204_0341'),
    ]

    operations = [
    ]
