# Generated by Django 5.1.5 on 2025-02-25 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_projectcollaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcollaborator',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectcollaborator',
            name='role',
            field=models.CharField(choices=[('viewer', 'Lecteur'), ('annotator', 'Annotateur'), ('editor', 'Éditeur'), ('admin', 'Administrateur')], default='viewer', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('viewer', 'Lecteur'), ('annotator', 'Annotateur'), ('editor', 'Éditeur'), ('admin', 'Administrateur')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée'), ('expired', 'Expirée')], default='pending', max_length=20)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
