# Generated by Django 5.1.5 on 2025-02-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_detectedobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='annotation_data',
        ),
        migrations.AddField(
            model_name='annotation',
            name='confidence',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='annotations/'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='label',
            field=models.CharField(default='Default Label', max_length=100),
        ),
        migrations.AddField(
            model_name='annotation',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annotation',
            name='x_max',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='x_min',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='y_max',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='annotation',
            name='y_min',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', max_length=20),
        ),
    ]
