# Generated by Django 5.1.6 on 2025-02-20 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_annotation_validated_at_annotation_validated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('modification_type', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression')], max_length=20)),
                ('previous_label', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_x_min', models.FloatField(blank=True, null=True)),
                ('previous_y_min', models.FloatField(blank=True, null=True)),
                ('previous_x_max', models.FloatField(blank=True, null=True)),
                ('previous_y_max', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.annotation')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Annotation histories',
                'ordering': ['-modified_at'],
            },
        ),
    ]
