# Generated by Django 5.2.17 on 2026-10-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_project_title_remove_project_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_annotation', 'Nouvelle annotation'), ('new_response', 'Nouvelle réponse'), ('project_published', 'Projet publié'), ('annotation_flagged', 'Annotation signalée'), ('project_invitation', 'Invitation à un projet')], max_length=20),
        ),
    ]
