# Generated by Django 5.1.6 on 2025-02-22 04:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_project_allow_community_annotations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dataitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dataset_images/'),
        ),
        migrations.AlterField(
            model_name='dataitem',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dataitem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
